source "vsphere-iso" "autogenerated_1" {
  CPUs                 = 2
  RAM                  = 4096
  #boot_command         = ["<esc><esc><esc><esc>e<wait>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del><del>", "linux /casper/vmlinuz --- autoinstall ds=\"nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>", "<enter><f10><wait>"]
  boot_command = [
    "c<wait>",
    "linux /casper/vmlinuz --- autoinstall",
    "<enter><wait>",
    "initrd /casper/initrd",
    "<enter><wait>",
    "boot",
    "<enter>"
  ]

  boot_wait            = "3s"
  cluster              = "${var.vsphere_cluster}"
  convert_to_template  = true
  datastore            = "${var.vsphere_datastore}"
  disk_controller_type = "${var.vm_disk_controller_type}"
  folder               = "${var.vsphere_folder}"
  guest_os_type        = "ubuntu64Guest"
  #http_directory       = "./http"
  #http_ip              = "192.168.100.188"
  insecure_connection  = true
  iso_checksum         = "sha256:8762f7e74e4d64d72fceb5f70682e6b069932deedb4949c6975d0f0fe0a91be3"
  iso_paths            = ["[${var.vsphere_datastore}]/${var.iso_folder}/${var.iso_file}"]

  cd_files = [
    "./http/meta-data",
    "./http/user-data"]
  cd_label = "cidata"

  network_adapters {
    network      = "${var.vsphere_portgroup_name}"
    network_card = "vmxnet3"
  }
  password               = "${var.vsphere_password}"
  shutdown_command       = "sudo shutdown -P now"
  ssh_handshake_attempts = 100
  ssh_password           = "ubuntu"
  ssh_port               = 22
  ssh_timeout            = "20m"
  ssh_username           = "ubuntu"
  storage {
    disk_size             = 40960
    disk_thin_provisioned = true
  }
  username       = "${var.vsphere_user}"
  vcenter_server = "${var.vsphere_server}"
  vm_name        = "${var.vsphere_template_name}"
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]
}
